### ISSUE TITLE
Work Organization

### ISSUE THREAD

**Issue by FrankBerrocal** [FrankBerrocal/Project4Lin3#1]
Identification of work distribution

**Comment by FrankBerrocal** [comment]
1.	Get a name:  4Lin3 Project.
2.	Work strategies:
a.	Resources
i.	Peter Kosa
ii.	Frank Berrocal
b.	Time
i.	1.5 months, expected delivery April 15th.
c.	Work and project organization
i.	GitHub Project and Repository
d.	Work
i.	Weekly Meetings to evaluate progress Fridays 10 am. 
ii.	Touchpoints on Tuesday 10:00 – 10:15 am.
1.	Status of work
2.	Requirements
3.	Roadblocks.
iii.	Modularized work.
1.	Each member will be assigned with balanced tasks to develop
2.	Each task should be able to connect with the work of the other members
iv.	Design
1.	UML  gadgets to capture all requirements.
2.	UML to represent the system.

**Comment by bluumann** [comment]
We agreed on this in today's meeting.
